from enum import StrEnum, auto

class SafetyClass(StrEnum):
    VERY_SAFE = "very_safe"
    SAFE = "safe"
    MODERATE = "moderate"
    CAUTION = "caution"
    DANGEROUS = "dangerous"
    UNSUITABLE = "unsuitable"
    UNCLASSIFIED = "unclassified"


cities =[
"Valletta, Malta",
"Qormi, Malta",
"Saint Paul's Bay, Malta",
"Birkirkara, Malta",
"Sliema, Malta",
"Mosta, Malta",
"Marsaskala, Malta",
"Żabbar, Malta",
"Naxxar, Malta",
"San Ġwann, Malta",
"San Ġiljan, Malta",
"Żebbuġ, Malta",
"Fgura, Malta",
"Żejtun, Malta",
"Rabat, Malta",
"Attard, Malta",
"Żurrieq, Malta",
"Mellieħa, Malta",
"Swieqi, Malta",
"Ħamrun, Malta",
"Birżebbuġa, Malta",
"Siġġiewi, Malta",
"Paola, Malta",
"Tarxien, Malta",
"Imsida, Malta",
"Gżira, Malta",
"Santa Venera, Malta",
"Victoria, Malta",
"Luqa, Malta",
"Cospicua, Malta",
"Xagħra, Malta",
"Għaxaq, Malta",
"Nadur, Malta",
"Marsa, Malta",
"Pietà, Malta",
"Balzan, Malta",
"Pembroke, Malta",
"Imġarr, Malta",
"Dingli, Malta",
"Marsaxlokk, Malta",
"Imqabba, Malta",
"Xewkija, Malta",
"Għajnsielem, Malta",
"Iklin, Malta",
"Lija, Malta",
"Kalkara, Malta",
"Gudja, Malta",
"Żebbuġ, Malta",
"Senglea, Malta",
"Għargħur, Malta",
"Qrendi, Malta",
"Vittoriosa, Malta",
"Imtarfa, Malta",
"Qala, Malta",
"Floriana, Malta",
"Kirkop, Malta",
"Safi, Malta",
"Sannat, Malta",
"Kerċem, Malta",
"Ta' Xbiex, Malta",
"Xgħajra, Malta",
"Għarb, Malta",
"Munxar, Malta",
"Fontana, Malta",
"San Lawrenz, Malta",
"Għasri, Malta",
"Imdina, Malta",
"Santa Luċija, Malta",]
